<?php
session_start(); require __DIR__.'/config.php';
if(empty($_SESSION['admin'])){header('Location: admin-login.php');exit;}
$db=getDb(); $success=''; $error=''; $month=preg_match('/^\d{4}-\d{2}$/',$_GET['month']??$_POST['award_month']??'')?($_GET['month']??$_POST['award_month']):date('Y-m'); $classYears=['C4C','C3C','C2C','C1C']; $uploadsDir=IMAGES_DIR;
function cotmFindAward(PDO $db,int $id):?array{$s=$db->prepare('SELECT * FROM cadet_of_month_awards WHERE id=?');$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null;}
function cotmEventName(?int $sid,string $class,string $name):string{return $sid===null?'Group Cadet of the Month — '.$name:'Cadet of the Month — '.$class.' — '.$name;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 try{
  if($action==='save_award'){
   $id=(int)($_POST['award_id']??0); $awardMonth=preg_match('/^\d{4}-\d{2}$/',$_POST['award_month']??'')?$_POST['award_month']:''; $raw=trim((string)($_POST['squadron_id']??'')); $sid=$raw===''?null:(int)$raw; $class=strtoupper(trim((string)($_POST['class_year']??''))); $name=trim((string)($_POST['cadet_name']??'')); $title=trim((string)($_POST['title']??'')); $desc=trim((string)($_POST['description']??'')); $points=($_POST['points_awarded']??'')!==''?(float)$_POST['points_awarded']:null;
   if(!$awardMonth)throw new RuntimeException('Select a valid award month.'); if($sid!==null&&!in_array($sid,array_map('intval',$db->query('SELECT id FROM squadrons')->fetchAll(PDO::FETCH_COLUMN)),true))throw new RuntimeException('Invalid squadron.'); if($sid===null)$class='GROUP';elseif(!in_array($class,$classYears,true))throw new RuntimeException('Invalid class year.'); if($name===''||$title===''||$desc==='')throw new RuntimeException('Cadet name, title/rank, and description are required.'); if($points===null||!is_finite($points))throw new RuntimeException('Enter a valid point value.');
   $existing=$id?cotmFindAward($db,$id):null; if($id&&!$existing)throw new RuntimeException('Award not found.');
   $photo=$existing['photo_filename']??null; $newPath=null; $oldPhoto=null;
   if(isset($_FILES['photo'])&&($_FILES['photo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){[$valid,$ext]=validateUploadedImage($_FILES['photo']);if(!$valid)throw new RuntimeException($ext);if(!is_dir($uploadsDir)&&!mkdir($uploadsDir,0755,true)&&!is_dir($uploadsDir))throw new RuntimeException('Unable to create the image directory.');$photo='cadet-of-month-'.bin2hex(random_bytes(12)).'.'.$ext;$newPath=$uploadsDir.'/'.$photo;if(!move_uploaded_file($_FILES['photo']['tmp_name'],$newPath))throw new RuntimeException('Failed to save the uploaded cadet photo.');$oldPhoto=$existing['photo_filename']??null;}
   $now=date('c'); $db->beginTransaction();
   if($existing){
    if(!empty($existing['event_id'])){$s=$db->prepare('UPDATE events SET squadron_id=?,event_name=?,value=?,points_awarded=?,timestamp=? WHERE id=? AND event_type=?');$s->execute([$sid,cotmEventName($sid,$class,$name),$points,$points,$now,(int)$existing['event_id'],'cadet_of_month']);if($s->rowCount()===0)throw new RuntimeException('The linked scoring entry could not be updated.');}
    else{$s=$db->prepare('INSERT INTO events(squadron_id,event_type,event_name,value,points_awarded,timestamp,created_at) VALUES(?,?,?,?,?,?,?)');$s->execute([$sid,'cadet_of_month',cotmEventName($sid,$class,$name),$points,$points,$now,$now]);$eventId=(int)$db->lastInsertId();$s=$db->prepare('UPDATE cadet_of_month_awards SET event_id=? WHERE id=?');$s->execute([$eventId,$id]);}
    $s=$db->prepare('UPDATE cadet_of_month_awards SET award_month=?,squadron_id=?,class_year=?,cadet_name=?,title=?,description=?,photo_filename=?,points_awarded=?,updated_at=? WHERE id=?');$s->execute([$awardMonth,$sid,$class,$name,$title,$desc,$photo,$points,$now,$id]);
   }else{
    $s=$db->prepare('INSERT INTO events(squadron_id,event_type,event_name,value,points_awarded,timestamp,created_at) VALUES(?,?,?,?,?,?,?)');$s->execute([$sid,'cadet_of_month',cotmEventName($sid,$class,$name),$points,$points,$now,$now]);$eventId=(int)$db->lastInsertId();
    $s=$db->prepare('INSERT INTO cadet_of_month_awards(award_month,squadron_id,class_year,cadet_name,title,description,photo_filename,points_awarded,event_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$awardMonth,$sid,$class,$name,$title,$desc,$photo,$points,$eventId,$now,$now]);
   }
   $db->commit(); if($oldPhoto&&$newPath){$oldPath=$uploadsDir.'/'.basename($oldPhoto);if(is_file($oldPath))@unlink($oldPath);} $success=$existing?'Cadet of the Month award updated.':'Cadet of the Month award created.';
  }elseif($action==='delete_award'){
   $id=(int)($_POST['award_id']??0);$award=cotmFindAward($db,$id);if(!$award)throw new RuntimeException('Award not found.');$db->beginTransaction();if(!empty($award['event_id'])){$s=$db->prepare('DELETE FROM events WHERE id=? AND event_type=?');$s->execute([(int)$award['event_id'],'cadet_of_month']);}$s=$db->prepare('DELETE FROM cadet_of_month_awards WHERE id=?');$s->execute([$id]);$db->commit();if(!empty($award['photo_filename'])){$p=$uploadsDir.'/'.basename($award['photo_filename']);if(is_file($p))@unlink($p);}$success='Award removed and its scoring entry was removed from the existing events ledger.';
  }
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();if(!empty($newPath)&&is_file($newPath))@unlink($newPath);$error=$e instanceof PDOException&&strpos($e->getMessage(),'UNIQUE')!==false?'That award slot already exists for this month. Edit the existing award instead.':$e->getMessage();}
}
$squadrons=$db->query('SELECT * FROM squadrons ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);$s=$db->prepare("SELECT a.*,s.name squadron_name FROM cadet_of_month_awards a LEFT JOIN squadrons s ON s.id=a.squadron_id WHERE a.award_month=? ORDER BY CASE WHEN a.squadron_id IS NULL THEN 0 ELSE 1 END,a.squadron_id,a.class_year");$s->execute([$month]);$awards=$s->fetchAll(PDO::FETCH_ASSOC);$map=[];foreach($awards as $a)$map[($a['squadron_id']===null?'group':$a['squadron_id']).':'.$a['class_year']]=$a;$monthLabel=date('F Y',strtotime($month.'-01'));
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manage Cadet of the Month</title>
<style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:20px;color:#222}.container{max-width:1200px;margin:0 auto}h1{color:#002147;text-align:center;margin:5px 0}.subtitle{text-align:center;color:#666;margin:0 0 20px}.month-form{display:flex;justify-content:center;gap:10px;align-items:end;margin-bottom:20px;flex-wrap:wrap}.month-form label{font-weight:bold}.month-form input{display:block;margin-top:4px;padding:8px;border:1px solid #ccc;border-radius:4px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px;align-items:start}.panel{background:#fff;border-radius:8px;box-shadow:0 1px 5px rgba(0,0,0,.14);padding:18px}.panel h2{margin:0 0 14px;color:#002147;border-bottom:2px solid #002147;padding-bottom:8px}.slot{border:1px solid #ddd;border-radius:6px;padding:12px;margin:10px 0;background:#fafafa}.slot-title{display:flex;justify-content:space-between;gap:8px;align-items:center;color:#002147;font-weight:bold;margin-bottom:10px}.slot-title small{color:#666;font-weight:normal}label{display:block;font-weight:bold;margin-top:9px}input[type=text],input[type=number],input[type=month],textarea{width:100%;padding:8px;margin-top:4px;border:1px solid #ccc;border-radius:4px;font:inherit}textarea{min-height:90px;resize:vertical}button{padding:8px 12px;border:0;border-radius:4px;background:#002147;color:#fff;cursor:pointer;font-weight:bold}.danger{background:#b00020}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.success,.error{padding:12px;border-radius:5px;margin-bottom:16px}.success{background:#e8f5e9;color:#1a7a1a}.error{background:#ffebee;color:#b00020}.preview{display:flex;gap:10px;align-items:center;margin-top:8px;color:#666;font-size:.9rem}.preview img{width:60px;height:75px;object-fit:cover;border-radius:4px}.back{text-align:center;margin-top:22px}.back a{color:#002147;font-weight:bold;text-decoration:none}@media(max-width:600px){body{padding:12px}.grid{grid-template-columns:1fr}.panel{padding:14px}}</style></head>
<body><div class="container"><h1>⭐ Manage Cadet of the Month</h1><p class="subtitle">Manage awards and their scoring entries for <?php echo htmlspecialchars($monthLabel); ?>.</p>
<?php if($success):?><div class="success"><?php echo htmlspecialchars($success);?></div><?php endif;?><?php if($error):?><div class="error"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<form class="month-form" method="get" action="admin-cadet-of-month.php"><label>Award Month<input type="month" name="month" value="<?php echo htmlspecialchars($month);?>"></label><button type="submit">Load Month</button></form>
<div class="grid">
<?php foreach($squadrons as $sq):?><section class="panel"><h2><?php echo htmlspecialchars($sq['name']);?></h2><?php foreach($classYears as $class):$a=$map[$sq['id'].':'.$class]??null;?><div class="slot"><div class="slot-title"><span><?php echo htmlspecialchars($class);?></span><small><?php echo $a?'+'.htmlspecialchars((string)$a['points_awarded']).' pts':'No award';?></small></div>
<form method="post" action="admin-cadet-of-month.php" enctype="multipart/form-data"><input type="hidden" name="action" value="save_award"><input type="hidden" name="award_id" value="<?php echo $a?htmlspecialchars((string)$a['id']):'0';?>"><input type="hidden" name="award_month" value="<?php echo htmlspecialchars($month);?>"><input type="hidden" name="squadron_id" value="<?php echo htmlspecialchars((string)$sq['id']);?>"><input type="hidden" name="class_year" value="<?php echo htmlspecialchars($class);?>">
<label>Cadet Name<input type="text" name="cadet_name" required value="<?php echo htmlspecialchars($a['cadet_name']??'');?>"></label><label>Title / Rank<input type="text" name="title" required placeholder="e.g. C3C" value="<?php echo htmlspecialchars($a['title']??$class);?>"></label><label>Description<textarea name="description" required placeholder="Why was this cadet selected?"><?php echo htmlspecialchars($a['description']??'');?></textarea></label><label>Points<input type="number" name="points_awarded" step="any" required value="<?php echo htmlspecialchars(isset($a['points_awarded'])?(string)$a['points_awarded']:'');?>"></label><label>Cadet Photo<input type="file" name="photo" accept="image/png,image/jpeg,image/gif,image/webp"></label>
<?php if($a&&!empty($a['photo_filename'])):?><div class="preview"><img src="<?php echo htmlspecialchars(iconUrl($a['photo_filename']));?>" alt=""><span>Current photo will be kept unless replaced.</span></div><?php endif;?><div class="actions"><button type="submit"><?php echo $a?'Update Award':'Save Award';?></button><?php if($a):?><button class="danger" type="submit" name="action" value="delete_award" onclick="return confirm('Remove this award and its scoring entry?');">Remove</button><?php endif;?></div></form></div><?php endforeach;?></section><?php endforeach;?>
<section class="panel"><h2>🏅 Group Cadet of the Month</h2><?php $a=$map['group:GROUP']??null;?><div class="slot"><div class="slot-title"><span>Group Award</span><small><?php echo $a?'+'.htmlspecialchars((string)$a['points_awarded']).' Group pts':'No award';?></small></div>
<form method="post" action="admin-cadet-of-month.php" enctype="multipart/form-data"><input type="hidden" name="action" value="save_award"><input type="hidden" name="award_id" value="<?php echo $a?htmlspecialchars((string)$a['id']):'0';?>"><input type="hidden" name="award_month" value="<?php echo htmlspecialchars($month);?>"><input type="hidden" name="squadron_id" value=""><input type="hidden" name="class_year" value="GROUP">
<label>Cadet Name<input type="text" name="cadet_name" required value="<?php echo htmlspecialchars($a['cadet_name']??'');?>"></label><label>Title / Rank<input type="text" name="title" required placeholder="e.g. C2C" value="<?php echo htmlspecialchars($a['title']??'');?>"></label><label>Description<textarea name="description" required placeholder="Why was this cadet selected for the Group award?"><?php echo htmlspecialchars($a['description']??'');?></textarea></label><label>Points<input type="number" name="points_awarded" step="any" required value="<?php echo htmlspecialchars(isset($a['points_awarded'])?(string)$a['points_awarded']:'');?>"></label><label>Cadet Photo<input type="file" name="photo" accept="image/png,image/jpeg,image/gif,image/webp"></label>
<?php if($a&&!empty($a['photo_filename'])):?><div class="preview"><img src="<?php echo htmlspecialchars(iconUrl($a['photo_filename']));?>" alt=""><span>Current photo will be kept unless replaced.</span></div><?php endif;?><div class="actions"><button type="submit"><?php echo $a?'Update Award':'Save Award';?></button><?php if($a):?><button class="danger" type="submit" name="action" value="delete_award" onclick="return confirm('Remove this award and its scoring entry?');">Remove</button><?php endif;?></div></form></div></section>
</div><div class="back"><a href="cadet-of-month.php?month=<?php echo htmlspecialchars($month);?>">View Public Page</a> · <a href="admin-panel.php">Back to Admin Panel</a></div></div></body></html>
