<?php
require __DIR__ . '/config.php';
require __DIR__ . '/theme-loader.php';
$theme=loadTheme(); $db=getDb();
$month=preg_match('/^\d{4}-\d{2}$/',$_GET['month']??'')?$_GET['month']:date('Y-m');
$stmt=$db->prepare("SELECT a.*,s.name squadron_name,s.icon_filename squadron_icon FROM cadet_of_month_awards a LEFT JOIN squadrons s ON s.id=a.squadron_id WHERE a.award_month=? ORDER BY CASE WHEN a.squadron_id IS NULL THEN 0 ELSE 1 END,a.squadron_id,a.class_year");
$stmt->execute([$month]); $awards=$stmt->fetchAll(PDO::FETCH_ASSOC);
$bySquadron=[]; $groupAward=null;
foreach($awards as $a){if($a['squadron_id']===null){$groupAward=$a;}else{$bySquadron[(int)$a['squadron_id']][$a['class_year']]=$a;}}
$squadrons=$db->query("SELECT * FROM squadrons ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
$classYears=['C4C','C3C','C2C','C1C']; $monthLabel=date('F Y',strtotime($month.'-01'));
$prevMonth=date('Y-m',strtotime($month.'-01 -1 month')); $nextMonth=date('Y-m',strtotime($month.'-01 +1 month'));
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cadet of the Month - Squadron Tracker</title><meta name="theme-color" content="<?php echo htmlspecialchars($theme['primary_color']??'#002147'); ?>">
<style>
:root{--primary-color:<?php echo htmlspecialchars($theme['primary_color']??'#002147'); ?>;--secondary-color:<?php echo htmlspecialchars($theme['secondary_color']??'#003366'); ?>}
*{box-sizing:border-box}body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:20px;color:#222}.container{max-width:1100px;margin:0 auto}
h1{color:var(--primary-color);text-align:center;margin:8px 0 4px}.subtitle{text-align:center;color:#666;margin:0 0 18px}.month-nav{display:flex;justify-content:center;align-items:center;gap:12px;margin:0 auto 24px;flex-wrap:wrap}.month-nav a{color:var(--primary-color);text-decoration:none;font-weight:bold}.month-label{font-size:1.05rem;font-weight:bold;min-width:130px;text-align:center}
.squadron-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:18px;align-items:start}.squadron-card,.group-card{background:#fff;border-radius:8px;box-shadow:0 1px 5px rgba(0,0,0,.14);overflow:hidden}.squadron-header,.group-header{background:var(--primary-color);color:#fff;padding:14px 16px;display:flex;align-items:center;gap:10px}.squadron-header img{width:38px;height:38px;object-fit:cover;border-radius:5px;background:#fff}.squadron-header h2,.group-header h2{font-size:1.1rem;margin:0}
.award-list{padding:12px}.award-slot{border:1px solid #e2e2e2;border-radius:7px;margin:8px 0;overflow:hidden;background:#fafafa}.award-slot.empty{padding:14px;color:#888}.award-slot-header{display:flex;justify-content:space-between;align-items:center;padding:8px 11px;background:#f0f2f5;font-size:.82rem;font-weight:bold;color:var(--primary-color)}.award-body{display:grid;grid-template-columns:92px 1fr;gap:12px;padding:12px}.cadet-photo{width:92px;height:112px;object-fit:cover;border-radius:5px;background:#ddd}.placeholder{width:92px;height:112px;border-radius:5px;background:#e5e5e5;display:flex;align-items:center;justify-content:center;color:#999;font-size:2rem}.cadet-name{font-size:1.03rem;font-weight:bold;color:#222;margin-bottom:2px}.cadet-title{font-size:.82rem;color:#666;margin-bottom:8px}.description{font-size:.88rem;line-height:1.45;color:#444;white-space:pre-line}.points{font-weight:bold;color:var(--primary-color);white-space:nowrap}.group-wrap{margin-top:24px}.group-card .award-body{grid-template-columns:120px 1fr}.group-card .cadet-photo,.group-card .placeholder{width:120px;height:145px}.empty-note{text-align:center;color:#888;padding:20px}.footer{text-align:center;margin:24px 0 8px;font-size:.9rem}.footer a{color:var(--primary-color);text-decoration:none;font-weight:bold}
@media(max-width:600px){body{padding:12px}.squadron-grid{grid-template-columns:1fr}.award-body,.group-card .award-body{grid-template-columns:76px 1fr;gap:10px}.cadet-photo,.group-card .cadet-photo,.placeholder,.group-card .placeholder{width:76px;height:100px}}
</style></head><body><div class="container">
<h1>⭐ Cadet of the Month</h1><p class="subtitle">USAFA Group 1 recognition · <?php echo htmlspecialchars($monthLabel); ?></p>
<div class="month-nav"><a href="?month=<?php echo htmlspecialchars($prevMonth); ?>">← <?php echo htmlspecialchars(date('M Y',strtotime($prevMonth.'-01'))); ?></a><span class="month-label"><?php echo htmlspecialchars($monthLabel); ?></span><?php if($month!==date('Y-m')):?><a href="?month=<?php echo htmlspecialchars($nextMonth); ?>"><?php echo htmlspecialchars(date('M Y',strtotime($nextMonth.'-01'))); ?> →</a><?php endif;?></div>
<div class="squadron-grid">
<?php foreach($squadrons as $squadron): $slots=$bySquadron[(int)$squadron['id']]??[]; ?><section class="squadron-card"><div class="squadron-header"><?php if(!empty($squadron['icon_filename'])):?><img src="<?php echo htmlspecialchars(iconUrl($squadron['icon_filename'])); ?>" alt=""><?php endif;?><h2><?php echo htmlspecialchars($squadron['name']); ?></h2></div><div class="award-list">
<?php foreach($classYears as $classYear): $award=$slots[$classYear]??null; ?><div class="award-slot <?php echo $award?'':'empty'; ?>"><div class="award-slot-header"><span><?php echo htmlspecialchars($classYear); ?></span><?php if($award):?><span class="points">+<?php echo htmlspecialchars((string)$award['points_awarded']); ?> pts</span><?php endif;?></div>
<?php if($award):?><div class="award-body"><?php if(!empty($award['photo_filename'])):?><img class="cadet-photo" src="<?php echo htmlspecialchars(iconUrl($award['photo_filename'])); ?>" alt="<?php echo htmlspecialchars($award['cadet_name']); ?>"><?php else:?><div class="placeholder">★</div><?php endif;?><div><div class="cadet-name"><?php echo htmlspecialchars($award['cadet_name']); ?></div><div class="cadet-title"><?php echo htmlspecialchars($award['title']); ?></div><div class="description"><?php echo htmlspecialchars($award['description']); ?></div></div></div><?php else:?><div style="padding-top:0">No award recorded.</div><?php endif;?></div><?php endforeach;?></div></section><?php endforeach;?>
</div>
<div class="group-wrap"><section class="group-card"><div class="group-header"><h2>🏅 Group Cadet of the Month</h2></div><?php if($groupAward):?><div class="award-body"><?php if(!empty($groupAward['photo_filename'])):?><img class="cadet-photo" src="<?php echo htmlspecialchars(iconUrl($groupAward['photo_filename'])); ?>" alt="<?php echo htmlspecialchars($groupAward['cadet_name']); ?>"><?php else:?><div class="placeholder">★</div><?php endif;?><div><div class="cadet-name"><?php echo htmlspecialchars($groupAward['cadet_name']); ?></div><div class="cadet-title"><?php echo htmlspecialchars($groupAward['title']); ?></div><div class="description"><?php echo htmlspecialchars($groupAward['description']); ?></div><div class="points" style="margin-top:10px">+<?php echo htmlspecialchars((string)$groupAward['points_awarded']); ?> Group pts</div></div></div><?php else:?><div class="empty-note">No Group Cadet of the Month award recorded.</div><?php endif;?></section></div>
<div class="footer"><a href="index.php">← Back to Group 1 Squadron Tracker</a></div></div></body></html>
